fixes #151
zharikovpro/railgun pull request #152
Opened 2017-05-27 13:59 UTC by Mifrill

2017-05-27 14:17 UTC, Mifrill commented
Locally tests passed
```
Finished in 23.4 seconds (files took 11.81 seconds to load)
92 examples, 0 failures
```

2017-05-27 20:03 UTC, zharikovpro commented
You should always check that coverage is 100%. Now coverage is (98.55%), and this is below the expected minimum coverage (100.00%).

2017-05-27 20:05 UTC, zharikovpro requested changes

2017-05-27 20:05 UTC, zharikovpro commented on spec/features/employee/administrator/user/administrator_edit_user_spec.rb
> +  so that user have beening  new credentials
cannot understand this paragraph. Feature is that administrator wants to edit user so that user has new data, and that's all.

2017-05-27 20:05 UTC, zharikovpro commented on spec/features/employee/administrator/user/administrator_edit_user_spec.rb
> +    When he fills in email 'new@mail.com' with no entering a password and clicks 'Update User' button
When he fills in email 'new@mail.com' and clicks 'Update User' button - this is enough.

2017-05-28 11:45 UTC, Mifrill commented
TODO login and logout without errors for  not employee user

2017-05-28 21:28 UTC, merged