fixes #200
zharikovpro/railgun pull request #202
Opened 2017-08-01 21:28 UTC by Mifrill

SolanoLabs unreasonably expensive in my humble opinion

2017-08-02 12:01 UTC, zharikovpro commented
Changeset looks big and complex. What happens here, what's the purpose of this PR?

2017-08-02 12:03 UTC, zharikovpro commented
To be more specific, I want to know the benefits of merging this into Railgun, compared to the current state.

2017-08-02 12:56 UTC, Mifrill commented
I'm not happy too  about A large number of commits and, this is due to the specific configuration of CI servers, for example Circel CI uses debian so there had to select specific settings for tests passed.
May be git rebase is help?

I wrote about the reasons in issue #200 , аfter a while, there was no reason not to do this
I already said that some repositories use several CI servers, so I decided that maybe there are reasons for this. Google answer: why not need to use several CI servers - had not give
Codecov and Codeclimate coverage report by token added
Headless gem for some VDS servers added (HEADLESS=on)
config for Travis, CircleCI, Codeship, Appveyor added

About  deploy RoR on WIndows is completely agree, this bad idea, but as I said in the Issue #200 , even the [official language repository](https://ci.appveyor.com/project/ruby/ruby/branch/trunk) uses this server

You can use your tokens for Codeclimate, Codecov, you URL for readme markdown icons against my.

If you think it's a useless job, remove this pr, no problem

2017-08-02 13:05 UTC, Mifrill commented
So you can check all builds on servers
[6 checks is passed](https://github.com/Mifrill/railgun/branches)

https://travis-ci.org/Mifrill/railgun
https://ci.appveyor.com/project/Mifrill/railgun
https://app.codeship.com/projects/236469
https://circleci.com/gh/Mifrill/railgun

2017-08-02 13:10 UTC, Mifrill commented
My quote:

> because sometimes the tests pass locally, but on the server tests are fail, this can help to find the cause faster and fix it.

Your quote:

> I don't understand: how another server will help in this case if one is not enough?

on another server i can see the problem and can fix it before you review the PR and tell me about why is CI server is failed as the same time locally tests is passed

2017-08-02 13:12 UTC, Mifrill commented
In addition, I really liked the possibility of displaying the percentage code coverage

2017-08-02 14:51 UTC, zharikovpro commented
> I'm not happy too about A large number of commits
> May be git rebase is help?

Sure yes, you can do git rebase and squash multiple commits into one. Then push with force.

> there was no reason not to do

Reson not to do - save efforts and keep solution simplier. There should be reasons to do, otherwise it's a wasted effort.

> I already said that some repositories use several CI servers, so I decided that maybe there are reasons for this

"They do it so let's do it too" is not a good reason if you don't understand the motivation behind this decision, it's pros and cons.

> why not need to use several CI servers - had not give
Codecov and Codeclimate coverage report by token added
Headless gem for some VDS servers added (HEADLESS=on)
config for Travis, CircleCI, Codeship, Appveyor added

Sorry, I don't understand this paragraph at all. Can you rewrite it with smaller sentences?) I still don't get the idea whats the benefit in supporting all these CI services at once, more than that - in one PR. Looks like a lot of "features" packed into one PR. With little benefits.

> on another server i can see the problem and can fix it before you review the PR and tell me about why is CI server is failed as the same time locally tests is passed

On which one you can see fail report? Surely there's no need to support all of these services to solve this issue. This PR does too much. Ideally, I'd like heroku CI expose results here, too. Will check if it's possible.

2017-08-02 14:52 UTC, zharikovpro commented
The ability to read CI report for collaborators in open source projects is a good intention and makes sense.

2017-08-02 14:54 UTC, zharikovpro commented
Also, about CI fails which works locally. It's quite an exceptional case. You should be able to run `bundle exec rspec CI=1` at all times and get same results as CI server, as a rule.

2017-08-02 14:55 UTC, zharikovpro commented
>  I really liked the possibility of displaying the percentage code coverage

Okay, and how this is related with current PR, what do you need for it?

2017-08-02 14:59 UTC, Mifrill commented
I thought that pr is directly related to the problem, so if the problem is related to significant changes (multiple CI servers), then in pr can include many changes

2017-08-02 15:03 UTC, zharikovpro commented
> I thought that pr is directly related to the problem

You listed several issues. One is that you can't read CI report. Do you need to add two services, make Headless flag and submit codecoverage token just to solve this one? I think not. This should be separate issue/PR.

Another issue is that you wanted to see nicer coverage report. Do you need to add two services, make Headless flag and submit codecoverage token just to solve this one? I think not. This should be separate issue/PR.

Do you need multiple CI server at all? I don't see the reason to answer "yes". Thus, this PR has at least 3 different issues in it.

2017-08-02 15:03 UTC, Mifrill commented
> Google answer: why not need to use several CI servers - had not give
Thats mean when i used google to find answer i had not a definite answer

> if you don't understand the motivation behind this decision

I cited the argument in the issue:
My quote:
> which means that you can position the application as a cross-platform application, and use the config file for deployed on any Paas or VDS

2017-08-02 15:06 UTC, zharikovpro commented
> Thats mean when i used google to find answer i had not a definite answer

And this means that you don't have to do it.

> which means that you can position the application

Already answered above, it's not the real benefit, not worth chasing.

2017-08-02 15:10 UTC, Mifrill commented
> Sorry, I don't understand this paragraph at all. Can you rewrite it with smaller sentences?)

My quote:

> Codecov and Codeclimate coverage report by token added
Headless gem for some VDS servers added (HEADLESS=on)
config for Travis, CircleCI, Codeship, Appveyor added

This is answer for your question.
     Your quote:

> What happens here, what's the purpose of this PR?

2017-08-02 15:12 UTC, zharikovpro commented
> Codecov and Codeclimate coverage report by token added

Storing any kind of secret tokens is a bad practice. What's the motivation, what's the benefit?

> Headless gem for some VDS servers added (HEADLESS=on)

What's the motivation, what's the benefit?

> config for Travis, CircleCI, Codeship, Appveyor added

What's the motivation, what's the benefit?

2017-08-02 15:13 UTC, zharikovpro commented
Also, if it's three different sentences please use a full stop to break sentences. Otherwise, it reads like a mess. Again, if you have real motivation to do all of these, create three different issues and PRs.

2017-08-02 15:14 UTC, Mifrill commented
ok, what if i'l keeped just one CI server, for example, Travis CI, and adding new PR, for codeclimate coverage report?

2017-08-02 15:15 UTC, Mifrill commented
Motivation:
 - About Travis CI server

> on another server i can see the problem and can fix it before you review the PR and tell me about why is CI server is failed as the same time locally tests is passed

2017-08-02 15:16 UTC, Mifrill commented
So when i used CI server i'l need to add headless gem - so this is include for one PR

2017-08-02 15:17 UTC, zharikovpro commented
> ok, what if i'l keeped just one CI server, for example, Travis CI

This is better. And remove anything else from this PR. 

> and adding new PR, for codeclimate coverage report?

Only if you don't add tokens, etc. I wonder what's the issue with running coverage report locally.

2017-08-02 15:18 UTC, zharikovpro commented
> So when i used CI server i'l need to add headless gem - so this is include for one PR

Please check [Travis docs](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode), it's not required anymore.

2017-08-02 15:26 UTC, Mifrill commented
Yeah my mistake, i had not see it (about headless Travis CI)

About token by Codeclimate test reporter, if keeped this in repo is this a problem, so why?
I understand that keeping  public tokens is unsafe, but it refers to a public check, and many repositories keep a token publicly

2017-08-02 15:30 UTC, Mifrill commented
so when i push coverage report by locally with token, the codeclimate server does not show this
You can test this yourself

2017-08-02 15:31 UTC, zharikovpro commented
> About token by Codeclimate test reporter, if keeped this in repo is this a problem, so why?

For the same reason as keeping your credit card credentials in a public repo.

Imagine that someone forked this repo. Now he will send reports from his repo to your account and mess them up. And you will see info about another repository (and also their source code, even if it was private). This is bad for both parties.

> and many repositories keep a token publicly

I'd love to take a look)

2017-08-02 15:34 UTC, Mifrill commented
https://github.com/bbatsov/rubocop/blob/master/.travis.yml

2017-08-02 15:52 UTC, Mifrill commented
https://github.com/search?q=CODECLIMATE_REPO_TOKEN&type=Code&utf8=%E2%9C%93

2017-08-02 15:59 UTC, Mifrill commented
i think that this happen becouse codeclimate coverage report just for master branch, so if anyone use your token and push report to server, the codeclimate server ignore that

2017-08-02 19:13 UTC, zharikovpro requested changes
Cleanup.

2017-08-02 19:13 UTC, zharikovpro commented on .travis.yml
> +  - CODECOV_TOKEN=e5f8d659-68e3-4dee-bbf7-96cda9a20a4d HEADLESS=on rake ci
Committing credentials considered a crime.

2017-08-02 19:13 UTC, zharikovpro commented on db/seeds.rb
> +administrator = FactoryGirl.create(:user, email: 'root@mail.com', password: 'password', password_confirmation: 'password')
Why changed? Looks redundant.

2017-08-02 19:13 UTC, zharikovpro commented on README.md
> +[![Coverage Status](https://img.shields.io/codeclimate/coverage/github/Mifrill/railgun.svg)](https://codeclimate.com/github/mifrill/railgun)
Coverage for this repo shouldn't display coverage from your repo. It should display coverage for zharikovpro/railgun repo, or skip it.

2017-08-02 19:13 UTC, zharikovpro commented on README.md
> +[![Build Status](https://travis-ci.org/Mifrill/railgun.svg?branch=master)](https://travis-ci.org/Mifrill/railgun)
Status for this repo shouldn't display status from your repo. It should display coverage for zharikovpro/railgun repo, or skip it.

2017-08-02 19:13 UTC, zharikovpro commented on .travis.yml
> +    - xvfb
No need.

2017-08-02 19:13 UTC, zharikovpro commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=0a7c2a9ff76974762fbe7151d5e4aa171f8a86682672d0b32d52ae46b10b3f44 bundle exec codeclimate-test-reporter
Okay, this is not a secret, just please move token to the env vars as in docs: https://docs.codeclimate.com/v1.0/docs/test-coverage-troubleshooting-tips#section--should-i-keep-my-test-coverage-token-secret-

2017-08-02 19:13 UTC, zharikovpro commented on .travis.yml
> +  - sudo apt-get install -y openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
No need for xvfb.

2017-08-03 08:36 UTC, Mifrill commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=0a7c2a9ff76974762fbe7151d5e4aa171f8a86682672d0b32d52ae46b10b3f44 bundle exec codeclimate-test-reporter
Okay, give me please your codeclimate token for markdown images too
https://docs.codeclimate.com/v1.0/docs/finding-your-test-coverage-token

2017-08-03 08:39 UTC, Mifrill commented on db/seeds.rb
> +administrator = FactoryGirl.create(:user, email: 'root@mail.com', password: 'password', password_confirmation: 'password')
https://github.com/zharikovpro/railgun/pull/191/files

when we starting to use standart devise authentificate for password, so the password: root is not valid anymore
https://github.com/zharikovpro/railgun/blob/master/config/initializers/devise.rb#L157

2017-08-03 08:42 UTC, zharikovpro commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=0a7c2a9ff76974762fbe7151d5e4aa171f8a86682672d0b32d52ae46b10b3f44 bundle exec codeclimate-test-reporter
861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe

2017-08-03 08:47 UTC, Mifrill commented
Please do not merge this PR yet. Travis CI is not working now
https://travis-ci.org/Mifrill/railgun/builds/260511857

Gem headless this is problem, your solution from [documenation](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode) is not helped

Fow now i find a way to passed Travis CI without gem headless, when i finished, I will report this

2017-08-03 09:11 UTC, zharikovpro commented on spec/spec_helper.rb
> +SimpleCov.minimum_coverage 100
Is there a reason to move line from one place to another?)

2017-08-03 09:12 UTC, zharikovpro commented on spec/spec_helper.rb
> -if ENV['CI']
This was required for Heroku, why remove?

2017-08-03 09:13 UTC, zharikovpro commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe bundle exec codeclimate-test-reporter
I managed to add this env var in Travis config. To follow best practices, pls remove token from that line, it will be in env already.

2017-08-03 09:14 UTC, zharikovpro requested changes
Please make changes, squash everything into one commit and rebase, then update the PR. Resulting commit should shortly describe end results, not all the history of failed attempts and changes.

2017-08-03 09:16 UTC, Mifrill commented
At the moment, I'm trying to figure it out with a git rebase.
For now it turns out badly, please ignore until any changes in this pr until I make a normal consisting of 2-3 commits with minimal changes

2017-08-03 09:18 UTC, zharikovpro commented
> At the moment, I'm trying to figure it out with a git rebase.

Remember that you can always create your local branches for experiments, and make a new PR if you need to. Best of luck!

> I make a normal consisting of 2-3 commits with minimal changes

Ideally, there should be one commit.

2017-08-03 09:20 UTC, Mifrill commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe bundle exec codeclimate-test-reporter
https://travis-ci.org/Mifrill/railgun/builds/260518609

Travis CI works with each variable in the neighborhood if it is specified as in the documentation, in this there is no sense to re-compile twice

2017-08-03 09:20 UTC, Mifrill commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe bundle exec codeclimate-test-reporter
This is the reason why I use this implementation

2017-08-03 09:23 UTC, zharikovpro commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe bundle exec codeclimate-test-reporter
I dont get it. My Travis setup has CODECLIMATE_REPO_TOKEN already in env. No need to add this into config, `bundle exec codeclimate-test-reporter` is enough.

2017-08-03 09:28 UTC, Mifrill commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe bundle exec codeclimate-test-reporter
https://monosnap.com/file/FjaM4YuHoNPU6HSauKaw1YNfOv150u

its 2 different builds, that's what I mean
It is possible to disable the Rails_ENV variable, will see what can i do, I understand and agree that it's ugly

2017-08-03 09:31 UTC, zharikovpro commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe bundle exec codeclimate-test-reporter
Build fails not because of the missing token. Just open the report and see the logs. This is what you wanted - now you have full access to them ;)

2017-08-03 09:34 UTC, Mifrill commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe bundle exec codeclimate-test-reporter
I'm not talking about the failure of the assembly.
  I say that Travis initializes two builds for each environment variable

2017-08-03 09:35 UTC, zharikovpro commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe bundle exec codeclimate-test-reporter
Oh, this is strange behavior. Shouldn't be like that for sure. Will read docs later.

2017-08-03 09:38 UTC, Mifrill commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe bundle exec codeclimate-test-reporter
Generally it's not, it's not strange, it's his feature, other servers do not do that, I ran into this when I connected it to the repository on node.js

https://github.com/bbatsov/rubocop/blob/master/.travis.yml

That's why this token is used when the command is not in the environment variable

2017-08-03 09:40 UTC, zharikovpro commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe bundle exec codeclimate-test-reporter
Okay, it may be like that in this case.

2017-08-03 09:40 UTC, zharikovpro commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe bundle exec codeclimate-test-reporter
Rubocop repository is a good example with trusted authority 👍

2017-08-03 09:55 UTC, Mifrill commented on .travis.yml
> +  - CODECLIMATE_REPO_TOKEN=861a17b4c76ddedf9972cdaca2771f9ab0c99f4ce92298fa965d25a4be55bdbe bundle exec codeclimate-test-reporter
If you mean this:
`addons:
  code_climate:
    repo_token:`
Well, my report was not formed with this setting, rather, report is went, but codeclimate did not show this report, that why i said:

> will see what can i do, I understand and agree that it's ugly

2017-08-03 19:31 UTC, Mifrill reviewed
For now you just need to login on Travis CI server and add your repository to check list, or we can to use my fork repo and my markdown icon, as you wish

2017-08-03 19:31 UTC, Mifrill commented on README.md
> +[![Build Status](https://travis-ci.org/zharikovpro/railgun.svg?branch=master)](https://travis-ci.org/zharikovpro/railgun)
I think that for correct work this icons you need to connect the repository `zharikovpro/railgun` on the server Travis CI

2017-08-04 20:08 UTC, zharikovpro approved these changes

2017-08-04 20:09 UTC, merged